service: serverless-kickstart
custom:
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage,'dev'}
  region: us-west-2
  environment:
    ENVIRONMENT: ${self:provider.stage}
    REGION: ${opt:region, self:provider.region}
    API_KEY_NAME: 'kickstart_api_key'
    SERVICE_ACCOUNT_SECRET_NAME: 'kickstart_service_account'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "arn:aws:secretsmanager:${opt:region, self:provider.region}:*:secret:${self:provider.environment.API_KEY_NAME}*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "arn:aws:secretsmanager:${opt:region, self:provider.region}:*:secret:${self:provider.environment.SERVICE_ACCOUNT_SECRET_NAME}*"


functions:
  serverless-cron:
    handler: handler.cron
    timeout: 600
    reservedConcurrency: 1
    events:
      - schedule: rate(1 hour)

package:
  exclude:
    - node_modules/**
    - .pytest_cache/**

plugins:
  - serverless-python-requirements